# user user-name;
worker_processes auto;

events {
  worker_connections 1024;
}

http {

  include mime.types;


  server {
    listen 443 ssl;
    server_name portfolio;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/ssl/portfolio_djebby_com.crt;
    ssl_certificate_key /etc/ssl/portfolio_djebby_com.key;

    location /api/ {
      proxy_pass http://<service-name>:<port>;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location / {
      try_files $uri /index.html =404;
    }
  }


  server {
    listen 80;
    listen [::]:80;
    server_name portfolio;

    location / {
      return 301 https://$host$request_uri;
    }
  }
}